import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sammed.Sankonatti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2> Lets build own social media for movies show and rating and etc etc etc .....</h2>
     
    </div>
  )
}
